### ISSUE TITLE
Update Front Page README

### ISSUE THREAD

**Issue by ScotteRoberts** [talent-path-la/class-notes#2]
The readme should have a general overview of each week, but if you want to know the specifics, you can dive deeper into the file structure.

**Comment by AbleLincoln** [comment]
Just put this document together for a curriculum overview. Some of this info might be transferable to the front page README

---

**Week 1: Tech overview, how the web works, Disney tour**

- Current events:  Google&#39;s role in shaping the modern web
  - read two articles and hold group discussion
- Compile a list of technologies we have heard about
  - Break list down into **core** tech that we will learn in the course, tech we will be **exposed** to, and tech that is **tangential** to what we are learning (consultants should learn these on their own)
- How the web works
  - Describe protocols, assets, servers, clients, DNS, infrastructure, etc.
- Example: serving a static site
  - Demo the complete process of serving a static site on the internet, from buying a domain to pushing to a server
- Group research projects
  - Research and present on four web topics: browser security, web protocols, web servers, browser wars
- Disney tour

**Week 2: Git, HTML, CSS, Web Design**

- Current events: the great divide between different kinds of frontend developers
- Git and Github: workflow, issue tracking
- HTML: semantic and accessible markup
- CSS: responsive design, flexbox, grid, animations
- Design principles: visual hierarchy, typography, accessibility, rhythm, color theory
- Portfolio project

**Week 3: Consulting 101, presentational skills, agile, scrum, Kanban**

- \&lt; JULIE CAN FILL THIS IN \&gt;
- Agile principles
- Storyboarding
- Scrum vs Kanban
- Agile in practice: project management with Github

**Week 4: JavaScript fundamentals**

- Basics: strings, arrays, numbers, objects
- ES6 features: arrow functions, callbacks, promises
- Advanced JS: web components, consuming APIs
- JS Cardio activity: pair programming fast-paced practice problems
- Project: Connect Four
- Project: WYSIWYG editor



**Week 5: Node.js, Express, server architecture and API design**

- Group project work begins
  - Project pitches, assign trainees to groups, create initial backlog of user stories
- Node server with text-based database
- RESTful API with Express
  - Discuss HTTP verbs, CRUD operations, and semantic API design
- Project: Message Board API
  - CRUD API for handling comment reading, writing, editing
  - Deployment with Heroku

**Week 6: React Week 1**

- React basics: state, props, data down/actions up, immutability
- Converting from vanilla HTML/JS to React
- Project: Message Board
  - Single Page Application for writing, editing, saving and displaying comments

**Week 7: React Week 2**

- Advanced React: routing, prop types
- Google Firebase with React
- Project: Pokémon Team Builder
  - Uses the open-source Pokéapi to display and manipulate Pokémon data
- Blizzard tour

**Week 8: Redux**

- Redux concepts: unidirectional data flow, store, actions, reducers
- Project: Trello clone
  - Mimics Trello functionality using Redux to manage state
- Community service: LA Food Bank

**Week 9: MongoDB, MERN stack**

- MongoDB concepts: NoSQL, JSON documents, collections
- Atlas: MongoDB cloud provider
- Mongoose: MongoDB object data modeling library for JavaScript
  - Models, schemas, and queries
- Database concepts: relationships between documents
- Project: persistent database for the Message Board app using MongoDB
  - Message Board as a full-stack application running on the MERN stack
  - Deployment with Netlify

**Week 10: Authentication and Security**

- User accounts on the backend
  - Passport: authentication library for Node
  - secure, hashed passwords
- Authentication and security with JSON web tokens

**Week 11: Interview practice**

- Computer science fundamentals: data structures, runtime analysis, time/space complexity, searching and sorting algorithms
- Whiteboard: practicing coding problems both in-person and online (with HackerRank)

**Week 12: Final Project Presentations**

- Cohort presents the beta releases of their group projects
